config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links do
    member do
      put "like" => "links#like"
      put "dislike" => "links#dislike"
    end

    resources :comments
  end

  root "links#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link

  validates :body, length: { minimum: 10 }
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :comments

  validates :title, length: { minimum: 5 }
  validates :url, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise(:database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable)
  has_many(:links)
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_link

  # GET link/{id}/comments or link/{id}/comments.json
  def index
    @comments = Comment.where(link_id: @link.id) # Comment.all
  end

  # GET link/{id}/comments/{id}
  def show
  end

  # GET link{id}/comments/new
  def new
    @comment = Comment.new
  end

  # GET link/{id}/comments/1/edit
  def edit
  end

  # POST link/{id}/comments or /comments.json
  def create
    puts ("*-*-*-*-*-*-*-* #{__method__}\n\tparams: #{params.inspect}")
    puts ("\t #{current_user.inspect}")

    @comment = @link.comments.new(comment_params())
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to link_comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [ :body, :link_id, :user_id ])
    end

    # before_action call to set_link and ensure that @link is found
    def set_link
      @link = Link.find(params[:link_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to request.referer || links_path, alert: "Link not found in  #{self.class}.#{__method__} - did a route or path get moved?? was that link_id removed??"
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    puts("*-*-* #{__method__}  #{current_user.inspect}")

    # A few ways to do this
    #  1)
    # lp = link_params()  # validate the incoming parameters
    # lp[:user_id] = current_user.id # add user_id to the has
    # @link = Link.new(lp)  # create the new link

    # 2) uses the current_user and grabs the `links` attribute of that user and then uses the build API
    #    note build is prefered whene there are associations
    # @link = current_user.links.build(link_params())

    # 3) uses the current_user and grabs the `links` attribute of that user and then uses the new API
    @link = current_user.links.new(link_params())

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_path, status: :see_other, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @link = Link.find(params[:id])
    if params[:format] == "like"
      @link.liked_by current_user
    elsif params[:format] == "unlike"
      @link.unliked_by current_user
    end
    redirect_back fallback_location: root_path
  end

  def dislike
    puts("*-*-* #{__method__}  #{current_user.inspect} #{params.inspect}")

    @link = Link.find(params[:id])
    if params[:format] == "dislike"
      @link.disliked_by current_user
    elsif params[:format] == "undislike"
      @link.undisliked_by current_user
    end
    redirect_back fallback_location: root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.expect(link: [ :title, :url ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<% if comment.created_at != nil %>
  <div id="<%= dom_id comment %>">
    <p>User <%= comment.user_id %> said: <pre><%= comment.body %></pre>
      <i><small><blockquote>last changed <%= time_ago_in_words(comment.updated_at) %> ago</blockquote></small></i>
    </p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [link, comment] ) do |form| %>
  
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Comment Text:", style: "display: block" %>
    <%= form.text_area :body, style: "width: 500px; height: 100px;" %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", link_comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>


  <h1>Comments for Link ID: <%= @link.id %></h1>

  <div id="comments">
    <% @comments.each do |comment| %>
      <%= render comment %>
      <p>
        <%# <%= link_to "Show this comment", comment %> 
      </p>
    <% end %>
  </div>

<%# <%= link_to "New comment", new_comment_path %> 

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment for link_id: <%= params[:link_id] %></h1>

<%= render Link.find(params[:link_id]) %>
<br/>
<%= render "form", link: @link, comment: @comment %>

<br>

<div>
  <%= link_to "Back to Link", @link  %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", link_comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Second Rails Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>

    <% if user_signed_in? %>
      <h2>Signed In</h2>
      <ul>
        <li>
          Signed in as <i>user_id: <%= current_user.id  %>  email: <%= current_user.email  %> </i>
        </li>
      </ul>
      <ul>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li><%= link_to "Change password", edit_user_password_path %></li>
        <li><%= link_to "Delete account", user_registration_path, method: :delete %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <h2>Not Signed In</h2>
      <ul>
        
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      </ul>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: @link) do |form| %>
  <% if @link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% @link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, style: "width: 500px;" %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url, style: "width: 500px;" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <strong>ID:</strong> <%= link.id %>&nbsp;&nbsp;
  <strong>Title:</strong> <%= link.title %>&nbsp;&nbsp;
  <strong>Url:</strong> <a href="<%= link.url %>"> <%= link.url %> </a>
  <br/>
  <blockquote><small> Submitted <%= time_ago_in_words(link.created_at) %> ago, by user_id: <%= link.user.id %> <%= link.user.email %></small></blockquote>
</div>

app/views/links/edit.html.erb
<% content_for :title, "Editing link" %>

<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Links" %>

<h1>Links</h1>


<div id="links"> 
  <% @links.each.with_index do |link, _| %>
    <div  style=" border: 1px solid black; ">
      <%= render link %>
      <% if user_signed_in? %>
        <% if current_user.liked? link %>
          <%= link_to 'unlike', like_link_path(link, 'unlike'), method: :put %>
        <% else %>
          <%= link_to 'like', like_link_path(link, 'like'), method: :put%>
        <% end %>
        <%= link.get_upvotes.size %>
        &nbsp;&nbsp;&nbsp;

        <% if current_user.disliked? link %>
          <%= link_to 'undislike', dislike_link_path(link, 'undislike'), method: :put%>
        <% else %>
          <%= link_to 'dislike', dislike_link_path(link, 'dislike'), method: :put %>
        <% end %>
        <%= link.get_downvotes.size %>
      <% end %>
      
      &nbsp;&nbsp;&nbsp;
      Number of Comments: <%= link.comments.size %>
      
      &nbsp;&nbsp;&nbsp;
      <%= link_to "Show this link", link %>

      &nbsp;&nbsp;&nbsp;
      <% if user_signed_in? %>
        <%= link_to "Add a comment for this link", new_link_comment_path(link) %>
      <% end %>

     
    </div>
  <% end %>
</div>

 <% if user_signed_in? %>
  <%= link_to "New link", new_link_path %>
<% end %>

app/views/links/new.html.erb
<% content_for :title, "New link" %>

<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<% if @link.comments.size < 1 %> 
  <h3>No comments yet!</h3>
<% else %>
  <h3>Comments:</h3>
  <blockquote>
  <div id="comments">
    <% @link.comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </div>
  </blockquote>
<% end %>

<% if user_signed_in? %>
  
  <%= #render the new commment form 
  render "comments/form", link: @link, comment: @link.comments.build  
  %>
<% end %>

<br/><br/>
<div>
  <% if @link.user == current_user %>
    <%= link_to "Edit this link", edit_link_path(@link) %> |
    <%= link_to "Destroy this link", @link, method: :delete, data: { confirm: 'Are you sure?' }%>
  <% end %>
  

  <br/><br/>
  <%= link_to "Back to links", links_path %>

</div>